### PR TITLE
configure husky

### PR DESCRIPTION
**Pull request by raajnadar**
### Motivation

Configure husky

### Test plan

Add a new commit to run lint pre-commit test.

### CODE REVIEW

**Comment by raajnadar** [comment]
`npm run lint --fix`??

**Comment by YIZHUANG** [comment]
Something like that. Also Husky need to be configured to do a `git add .` after that.

**Comment by raajnadar** [comment]
The lint issues should be fixed on file save. Instead of fixing them on commit (My vscode config does this automatically on save).

We should not add `git add .` with a pre-commit hook because if the users need to do partial commit all the files will be staged which is not the desired outcome right?? Then the user need to unstage file for partial commit.

**Comment by YIZHUANG** [comment]
I actually don't have the lint on save, it also depends on the editor you are using.

**Comment by raajnadar** [comment]
The CI will fail we need to fix the 2 error which I couldn't resolve

**Pull request merged**
