### PR TITLE
resetTotalItems on children changes

### PR DESCRIPTION
**Pull request by abhinavdalal-iconnect**

### CODE REVIEW

**Comment by abhinavdalal-iconnect** [comment]
this PR is the second part of #71

**Comment by abhinavdalal-iconnect** [comment]
@YIZHUANG let me know if any changes needed.. 
one additional scenario i covered is onResize to smaller screen and then we have enough children; we now call setClones with the resetCurrentSlide flag set to true..

**Comment by abhinavdalal-iconnect** [comment]
@YIZHUANG could you please test, merge and release these changes

**Comment by YIZHUANG** [comment]
Hi sorry for the wait as i havent been in a good place recenctly will review it asap after i left.

**Pull request merged**
