### PR TITLE
Updates types.ts to provide typings for ref usage

### PR DESCRIPTION
**Pull request by tpinne**
When using a ref with the Carousel these typings ensure to provide available methods/members to the user.

Feel free to add more methods/members if they are useful to use with a ref.

### CODE REVIEW

**Comment by YIZHUANG** [comment]
Hi, thank you for the PR. How can i test this?

**Comment by tpinne** [comment]
The following snippet is a c&p stripped down version of our code and not tested if it really runs as it is:

```typescript
import React, { FunctionComponent, useEffect, useRef } from 'react';
import Carousel from 'react-multi-carousel';

const RefTest: FunctionComponent = () => {
  const carouselRef = useRef<Carousel | null>(null);
  
  const activeIndex = 3;
  
  useEffect(() => {
    if (carouselRef && carouselRef.current) {
      carouselRef.current.goToSlide(activeIndex);
    }
  }, [carouselRef]);
  
  return (
    <Carousel
      ref={carouselRef}
      responsive={{
        all: {
          breakpoint: {
            min: 0,
            max: 3000,
          },
          items: 1,
        },
      }}
      slidesToSlide={1}
    >
      {Array(8).fill(0).map((item, index) => (
        <div>#{index}</div>
      ))}
    </Carousel>
  )
};

export default RefTest;
```

In general this code should slide the carousel to slide 3 instantly after mount. This works already without this PR but you have no coding assistance (at least in IntelliJ based products) and TS throws an error on the following line, because TS doesn't know that `goToSlide` exists on `Carousel`.

```typescript
carouselRef.current.goToSlide(activeIndex);
```

So with this PR there should be no compile errors with TS and coding assistance. And it makes sense to add every public method from `Carousel` to the interface which could be useful for a developer to interact with the instance directly (like next, previous and state, ...).

**Comment by YIZHUANG** [comment]
Cool, thank you for bringing this up. I didn't notice this before. I will add a few more methods and then merge this.

**Comment by YIZHUANG** [comment]
It's now at 2.1.2.

**Pull request merged**
