### PR TITLE
Remove partialVisibilityGutter when there is not enough children

### PR DESCRIPTION
**Pull request by YIZHUANG**

### CODE REVIEW

**Comment by YIZHUANG** [comment]
> Wow! This looks so much cleaner now.. I'll test it over the weekend and let you know if it changes anything..

Thank you.

**Comment by abhinavdalal** [comment]
@YIZHUANG looks good to me.. i have tested manually.. will try to work to make a pr to add test cases for notEnoughChildren.. resize and children changes should trigger correct functions..

**Comment by groomain** [comment]
I think we still have the problem after this fix : https://codesandbox.io/s/cool-darkness-368tg?file=/src/App.js

**Comment by krunalMahaleCactus** [comment]
@abhinavdalal there is issue here.

function notEnoughChildren(state: CarouselInternalState): boolean {
  const { slidesToShow, totalItems } = state;
  return totalItems <= slidesToShow; // this should be less then or equal
}

**Comment by abhinavdalal** [comment]
@krunalMahaleCactus  would you be able to create a PR with relevant test cases to make it easier to understand why it should be less than or equal and not less than.. i see the original code (before this PR) also had less than..
I guess the case i am not sure about is if the totalItems == slidesToShow and we want to be able to show the partial visibility in a circular manner if partial visibility is true? I need to think it through more..

**Pull request merged**
