### PR TITLE
Fix partialVisibilityGutter when showing more than one slide

### PR DESCRIPTION
**Pull request by Adrian3PG**

### CODE REVIEW

**Comment by abhinavdalal** [comment]
actually the more i think about it.. if i have 3 items on the page.. say screen is 600px; the itemWidth is 200px as 600 / 3. Now because of partialVisibile 4th item (partialVisibleGutter is 60px say).. i need to make the item width 180px so that i have the total of 60px at the end extra.. so i think the current code is correct!

**Comment by Adrian3PG** [comment]
The current code would subtract 60 from each item. So each item would be 200 - 60px = 140px instead of 180px

**Comment by abhinavdalal** [comment]
aahh i see you are correct... makes sense!

**Comment by abhinavdalal** [comment]
@Adrian3PG would be awesome if can add tests..
@YIZHUANG pls release when you get a chance

**Comment by Adrian3PG** [comment]
I tried to write a quick integration test, but failed and I'm swamped in my work and meetings today.  So I don't think I can write one this week 😞

**Comment by YIZHUANG** [comment]
@all-contributors please add @Adrian3PG  for code

**Pull request merged**
