### PR TITLE
[Feature] Basic styled components support

### PR DESCRIPTION
**Pull request by tpinne**
Adds the standard `className` prop and renders it to the container so you're able to this:

```jsx
import styled from 'styled-component';
import Carousel from 'react-multi-carousel';

const CrazyCarousel = styled(Carousel)`
  background: lime;
  border: 10px solid yellow;

  .react-multi-carousel-track {
    background: purple;
  }
`;

// ...

const MyComponent = () => <CrazyCarousel {...someProps} />
```

### CODE REVIEW

**Comment by YIZHUANG** [comment]
Isn't ```containerClass``` the same as the ```className```?

**Comment by tpinne** [comment]
> Isn't `containerClass` the same as the `className`?

Yes, it is the same location, but https://www.styled-components.com/docs/basics#styling-any-component sets the standard prop `className` to its generated class name on the component you want to style. And you can't afiak configure the prop to use. Neither globally (what you wouldn't want anyway) nor locally for a specific usage.

**Comment by YIZHUANG** [comment]
> > Isn't `containerClass` the same as the `className`?
> 
> Yes, it is the same location, but https://www.styled-components.com/docs/basics#styling-any-component sets the standard prop `className` to its generated class name on the component you want to style. And you can't afiak configure the prop to use. Neither globally (what you wouldn't want anyway) nor locally for a specific usage.

Sounds good, thank you!

**Comment by YIZHUANG** [comment]
It's now in 2.1.1

**Comment by tpinne** [comment]
Thx, OSS at it's best!

**Comment by YIZHUANG** [comment]
@all-contributors please add @tpinne for code.

**Pull request merged**
