### PR TITLE
Added "Rewind" option

### PR DESCRIPTION
**Pull request by MaSchVam**
As proposed in #330 I have added a "Rewind" option (`rewind` _bool_ prop) that can be utilized if infinite mode is not opted into, but autoplay **explicitly** is.  When the last slide is hit with this configuration of props, the autoplay interval is reset and the carousel is set back to slide `0`, with a potential custom transition duration and custom autoplay speed in mind.

### CODE REVIEW

**Comment by YIZHUANG** [comment]
Good stuff, can you also update the documentation as well?

**Comment by YIZHUANG** [comment]
Good stuff, can you also update the documentation as well?

**Comment by MaSchVam** [comment]
> Good stuff, can you also update the documentation as well?

Thanks! I updated the README with the `rewind` prop, and added clarification to the infinite prop in the documentation as well, to make people aware of the fact that carousel items are cloned with this option.

**Comment by MaSchVam** [comment]
@YIZHUANG Let me know if I can do more.

**Comment by YIZHUANG** [comment]
I haven't tested this yet, but looks good, i will test it before making the release

**Review by YIZHUANG — APPROVED** [review]

**Pull request merged**
